### ISSUE TITLE
mv_ddr-armada-atf-mainline does not follow atf

### ISSUE THREAD

**Issue by ggardet** [MarvellEmbeddedProcessors/mv-ddr-marvell#28]
`mv_ddr-armada-atf-mainline` branch was not updated since 2018 and atf 2.4 does not build with this branch.

**Comment by pali** [comment]
That is because mentioned branch is old. Currently the latest branch is `mv-ddr-devel`:
https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell/tree/mv-ddr-devel

**Comment by pali** [comment]
@ggardet: If you want to use revent ATF you need to use also recent mv-ddr-marvell code from the latest branch.

It is also documented in the ARM Trusted Firmware documentation:
https://trustedfirmware-a.readthedocs.io/en/latest/plat/marvell/armada/build.html

**Comment by ggardet** [comment]
Indeed, using `mv-ddr-devel` branch fixes the build. Thanks.

**Comment by pali** [comment]
There is now also `master` branch.
