### ISSUE TITLE
GCC-10 compile errors

### ISSUE THREAD

**Issue by pali** [MarvellEmbeddedProcessors/mv-ddr-marvell#30]
In Marvell SDK for mv-ddr sources is available patch *fix compilation errors popped up by GCC-10* which is not present in this mv-ddr-marvell github repository.

@kostapr: Could you please include mentioned patch which fixes compilation under gcc-10 into this mv-ddr-marvell github repository?

**Comment by kostapr** [comment]
done

**Comment by pali** [comment]
thanks!
